services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSIONS: ${NODE_VERSIONS:-16 18 20}
        NPM_VERSION: latest

    volumes:
      - ..:/workspace:cached
      - vscode-extension:/root/.vscode-server

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  vscode-extension:
